### PR TITLE
Science Collections

### PR DESCRIPTION
**Pull request by deoyani**
@RayPlante 
This is still a work in progress branch where we are updating changes and updates in metadata schema to accommodate science collections.

### CODE REVIEW

**Comment by RayPlante** [comment]
You'll need to fix your examples as well, yes?

**Comment by deoyani** [comment]
@RayPlante  This branch is updated with all your changes.

**Review by RayPlante — APPROVED** [review]
I'm replacing this PR with #51 to resolve conflicts.

**Comment by RayPlante** [comment]
See #51

**Pull request closed without merging**
